spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  # 使用 Druid 数据源
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL 驱动
    url: jdbc:mysql://localhost:3306/nacos?useUnicode=true&characterEncoding=utf8mb4&serverTimezone=UTC&useSSL=false  # 数据库连接 URL
    username: root  # 数据库用户名
    password: root  # 数据库密码
    # Druid 配置
    druid:
      initial-size: 5  # 初始连接池大小
      min-idle: 5  # 最小空闲连接数
      max-active: 20  # 最大连接池数量
      max-wait: 60000  # 获取连接时最大等待时间

