spring:
  application:
    name: llm
  ai:
    openai:
      api-key: "sk-f755ab0f995c43ffa206424bb2c43de2"
      base-url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
      chat:
        options:
          model: "deepseek-v3"

langchain4j:
  models:
    deepseek-v3:
      apiKey: "sk-f755ab0f995c43ffa206424bb2c43de2"
      modelName: "deepseek-v3"
      baseUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1"
    qwen-turbo:
      apiKey: "sk-f755ab0f995c43ffa206424bb2c43de2"
      modelName: "qwen-turbo"
      baseUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1"
  stream-models:
    deepseek-r1:
      apiKey: "sk-f755ab0f995c43ffa206424bb2c43de2"
      modelName: "deepseek-r1"
      baseUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1"
    deepseek-v3:
      apiKey: "sk-f755ab0f995c43ffa206424bb2c43de2"
      modelName: "deepseek-v3"
      baseUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1"
  embeddings:
    text-embedding-v3:
      apiKey: "sk-f755ab0f995c43ffa206424bb2c43de2"
      modelName: "text-embedding-v3"
      baseUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1"
    text-embedding-v2:
      apiKey: "sk-f755ab0f995c43ffa206424bb2c43de2"
      modelName: "text-embedding-v2"
      baseUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1"



