spring:
  application:
    name: llm

langchain4j:
  models:
    deepseek-v3:
      apiKey: "sk-f755ab0f995c43ffa206424bb2c43de2"
      modelName: "deepseek-v3"
      baseUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1"
    qwen-turbo:
      apiKey: "sk-f755ab0f995c43ffa206424bb2c43de2"
      modelName: "qwen-turbo"
      baseUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1"




